// Code generated by "stringer -type=StringID"; DO NOT EDIT.

package resources

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[YourJournalIsNowOpen-0]
	_ = x[NewEntryDraftExists-1]
	_ = x[YouCanNowCreateYourEntry-2]
	_ = x[YouCanNowCreateYourEntry_succinct-3]
	_ = x[ForDate-4]
	_ = x[IRepeat-5]
	_ = x[NextPartPleaseReprompt-6]
	_ = x[YourEntryIsEmptyNoRepeat-7]
	_ = x[YourEntryIsEmptyNoCorrect-8]
	_ = x[OkayCorrectPart-9]
	_ = x[CorrectPartReprompt-10]
	_ = x[NewEntryAborted-11]
	_ = x[YourEntryIsEmptyNoSave-12]
	_ = x[NewEntryConfirmation-13]
	_ = x[NewEntryConfirmationReprompt-14]
	_ = x[OkaySaved-15]
	_ = x[OkayNotSaved-16]
	_ = x[SuccinctModeExplanation-17]
	_ = x[WhatDoYouWantToDoNext-18]
	_ = x[DidNotUnderstandTryAgain-19]
	_ = x[ExampleRelativeDateQuery-20]
	_ = x[ExampleDateQuery-21]
	_ = x[CouldNotGetEntry-22]
	_ = x[CouldNotGetEntries-23]
	_ = x[NoEntriesInTimeRangeFound-24]
	_ = x[EntriesInTimeRange-25]
	_ = x[ReadEntry-26]
	_ = x[JournalIsEmpty-27]
	_ = x[NewEntryExample-28]
	_ = x[EntryForDateNotFound-29]
	_ = x[SearchError-30]
	_ = x[SearchNoResultsFound-31]
	_ = x[SearchResults-32]
	_ = x[DeleteEntryNotFound-33]
	_ = x[DeleteEntryCouldNotGetEntry-34]
	_ = x[DeleteEntryConfirmation-35]
	_ = x[DeleteEntryError-36]
	_ = x[OkayDeleted-37]
	_ = x[OkayNotDeleted-38]
	_ = x[LinkWithGoogleAccount-39]
	_ = x[OkayWillBeSuccinct-40]
	_ = x[OkayWillBeVerbose-41]
	_ = x[InvalidDate-42]
	_ = x[InternalError-43]
	_ = x[Help-44]
	_ = x[Done-45]
	_ = x[Correct1-46]
	_ = x[Correct2-47]
	_ = x[Repeat1-48]
	_ = x[Repeat2-49]
	_ = x[Abort-50]
	_ = x[ShortPause-51]
	_ = x[LongPause-52]
	_ = x[DriveCannotCreateFileError-53]
	_ = x[DriveMultipleFilesFoundError-54]
	_ = x[DriveSheetNotFoundError-55]
	_ = x[DriveUnknownError-56]
	_ = x[Journal-57]
	_ = x[EndMarker-58]
}

const _StringID_name = "YourJournalIsNowOpenNewEntryDraftExistsYouCanNowCreateYourEntryYouCanNowCreateYourEntry_succinctForDateIRepeatNextPartPleaseRepromptYourEntryIsEmptyNoRepeatYourEntryIsEmptyNoCorrectOkayCorrectPartCorrectPartRepromptNewEntryAbortedYourEntryIsEmptyNoSaveNewEntryConfirmationNewEntryConfirmationRepromptOkaySavedOkayNotSavedSuccinctModeExplanationWhatDoYouWantToDoNextDidNotUnderstandTryAgainExampleRelativeDateQueryExampleDateQueryCouldNotGetEntryCouldNotGetEntriesNoEntriesInTimeRangeFoundEntriesInTimeRangeReadEntryJournalIsEmptyNewEntryExampleEntryForDateNotFoundSearchErrorSearchNoResultsFoundSearchResultsDeleteEntryNotFoundDeleteEntryCouldNotGetEntryDeleteEntryConfirmationDeleteEntryErrorOkayDeletedOkayNotDeletedLinkWithGoogleAccountOkayWillBeSuccinctOkayWillBeVerboseInvalidDateInternalErrorHelpDoneCorrect1Correct2Repeat1Repeat2AbortShortPauseLongPauseDriveCannotCreateFileErrorDriveMultipleFilesFoundErrorDriveSheetNotFoundErrorDriveUnknownErrorJournalEndMarker"

var _StringID_index = [...]uint16{0, 20, 39, 63, 96, 103, 110, 132, 156, 181, 196, 215, 230, 252, 272, 300, 309, 321, 344, 365, 389, 413, 429, 445, 463, 488, 506, 515, 529, 544, 564, 575, 595, 608, 627, 654, 677, 693, 704, 718, 739, 757, 774, 785, 798, 802, 806, 814, 822, 829, 836, 841, 851, 860, 886, 914, 937, 954, 961, 970}

func (i StringID) String() string {
	if i < 0 || i >= StringID(len(_StringID_index)-1) {
		return "StringID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StringID_name[_StringID_index[i]:_StringID_index[i+1]]
}
