// Code generated by "stringer -type=StringID"; DO NOT EDIT.

package resources

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[YourJournalIsNowOpen-0]
	_ = x[NewEntryDraftExists-1]
	_ = x[YouCanNowCreateYourEntry-2]
	_ = x[YouCanNowCreateYourEntry_succinct-3]
	_ = x[ForDate-4]
	_ = x[IRepeat-5]
	_ = x[NextPartPlease-6]
	_ = x[YourEntryIsEmptyNoRepeat-7]
	_ = x[YourEntryIsEmptyNoCorrect-8]
	_ = x[OkayCorrectPart-9]
	_ = x[CorrectPart-10]
	_ = x[NewEntryAborted-11]
	_ = x[YourEntryIsEmptyNoSave-12]
	_ = x[NewEntryConfirmation-13]
	_ = x[NewEntryConfirmationReprompt-14]
	_ = x[OkaySaved-15]
	_ = x[OkayNotSaved-16]
	_ = x[SuccinctModeExplanation-17]
	_ = x[WhatDoYouWantToDoNext-18]
	_ = x[DidNotUnderstandTryAgain-19]
	_ = x[ExampleRelativeDateQuery-20]
	_ = x[ExampleDateQuery-21]
	_ = x[CouldNotGetEntry-22]
	_ = x[CouldNotGetEntries-23]
	_ = x[NoEntriesInTimeRangeFound-24]
	_ = x[EntriesInTimeRange-25]
	_ = x[ReadEntry-26]
	_ = x[JournalIsEmpty-27]
	_ = x[NewEntryExample-28]
	_ = x[EntryForDateNotFound-29]
	_ = x[SearchError-30]
	_ = x[SearchNoResultsFound-31]
	_ = x[SearchResults-32]
	_ = x[DeleteEntryNotFound-33]
	_ = x[DeleteEntryCouldNotGetEntry-34]
	_ = x[DeleteEntryConfirmation-35]
	_ = x[DeleteEntryError-36]
	_ = x[OkayDeleted-37]
	_ = x[OkayNotDeleted-38]
	_ = x[LinkWithGoogleAccount-39]
	_ = x[OkayWillBeSuccinct-40]
	_ = x[OkayWillBeVerbose-41]
	_ = x[InvalidDate-42]
	_ = x[InternalError-43]
	_ = x[Help-44]
	_ = x[ShortPause-45]
	_ = x[LongPause-46]
	_ = x[EndMarker-47]
}

const _StringID_name = "YourJournalIsNowOpenNewEntryDraftExistsYouCanNowCreateYourEntryYouCanNowCreateYourEntry_succinctForDateIRepeatNextPartPleaseYourEntryIsEmptyNoRepeatYourEntryIsEmptyNoCorrectOkayCorrectPartCorrectPartNewEntryAbortedYourEntryIsEmptyNoSaveNewEntryConfirmationNewEntryConfirmationRepromptOkaySavedOkayNotSavedSuccinctModeExplanationWhatDoYouWantToDoNextDidNotUnderstandTryAgainExampleRelativeDateQueryExampleDateQueryCouldNotGetEntryCouldNotGetEntriesNoEntriesInTimeRangeFoundEntriesInTimeRangeReadEntryJournalIsEmptyNewEntryExampleEntryForDateNotFoundSearchErrorSearchNoResultsFoundSearchResultsDeleteEntryNotFoundDeleteEntryCouldNotGetEntryDeleteEntryConfirmationDeleteEntryErrorOkayDeletedOkayNotDeletedLinkWithGoogleAccountOkayWillBeSuccinctOkayWillBeVerboseInvalidDateInternalErrorHelpShortPauseLongPauseEndMarker"

var _StringID_index = [...]uint16{0, 20, 39, 63, 96, 103, 110, 124, 148, 173, 188, 199, 214, 236, 256, 284, 293, 305, 328, 349, 373, 397, 413, 429, 447, 472, 490, 499, 513, 528, 548, 559, 579, 592, 611, 638, 661, 677, 688, 702, 723, 741, 758, 769, 782, 786, 796, 805, 814}

func (i StringID) String() string {
	if i < 0 || i >= StringID(len(_StringID_index)-1) {
		return "StringID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _StringID_name[_StringID_index[i]:_StringID_index[i+1]]
}
